/**
 * Action types
 */
export const FETCH_RESTAURANTS_REQUEST = 'FETCH_RESTAURANTS_REQUEST'
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS'
export const FETCH_RESTAURANTS_FAILURE = 'FETCH_RESTAURANTS_FAILURE'
export const SELECT_RESTAURANT         = 'SELECT_RESTAURANT'
export const SUGGEST_RESTAURANT        = 'SUGGEST_RESTAURANT'