/**
 * Action types
 */
export default {
  FETCH_RESTAURANTS_REQUEST: 'FETCH_RESTAURANTS_REQUEST',
  FETCH_RESTAURANTS_SUCCESS: 'FETCH_RESTAURANTS_SUCCESS',
  FETCH_RESTAURANTS_FAILURE: 'FETCH_RESTAURANTS_FAILURE'
}